[package]
name = "pixelpwnr-server"
version = "0.1.0"
authors = ["timvisee <timvisee@gmail.com>"]

[dependencies]
pixelpwnr-render = { path = "../pixelpwnr-render" }
# pixelpwnr-render = { git = "https://github.com/timvisee/pixelpwnr-render.git" }
